name: Automated build/lint/test for typescript

# Run on every push, PR event, and if run manually in Github actions console
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build/lint/test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        # Since we currently only use the 14.x runtime in lambda, using the same here.

    steps:
      - name: Checkout commit
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM packages
        run: npm ci
      - name: Run eslint, prettier, and tsc
        run: npm run lint
      - name: Run unit tests with coverage report
        run: npm run coverage
      # Uncomment once ready to deploy to prod on each master branch build
      #- name: Deploy to production
      #  if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      #  run: npm run serverless -- deploy --stage prod
      #  with:
      #    access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #    secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #    region: us-east-1
